[package]
name = "lab"
version = "0.1.0"
edition = "2021"

[dependencies]
qtcloud-think-cli = { path = "../../apps/qtcloud-think/src/cli" }
quanttide-think = { path = "../../packages/quanttide-think-toolkit/packages/rust" }
quanttide-agent = { path = "../../packages/quanttide-agent-toolkit/packages/rust" }
